# Generated by Django 3.1 on 2020-09-03 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20200903_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90, verbose_name='제품명')),
                ('img_url', models.URLField(blank=True, verbose_name='이미지주소')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='수정날짜')),
                ('hits', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'verbose_name': '게시글',
                'verbose_name_plural': '게시글',
                'db_table': 'post',
            },
        ),
        migrations.CreateModel(
            name='Post_recomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postside.post')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'verbose_name': '게시글 추천',
                'verbose_name_plural': '게시글 추천',
                'db_table': 'post_recomment',
            },
        ),
        migrations.CreateModel(
            name='Post_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.URLField(blank=True)),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postside.post')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'verbose_name': '게시글 코멘트',
                'verbose_name_plural': '게시글 코멘트',
                'db_table': 'post_comment',
            },
        ),
        migrations.CreateModel(
            name='Like_post_recomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.IntegerField(default=0, verbose_name='좋아요')),
                ('bad', models.IntegerField(default=0, verbose_name='싫어요')),
                ('post_recomment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postside.post_recomment')),
            ],
        ),
        migrations.CreateModel(
            name='Like_post_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.IntegerField(default=0, verbose_name='좋아요')),
                ('bad', models.IntegerField(default=0, verbose_name='싫어요')),
                ('post_comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postside.post_comment')),
            ],
        ),
    ]
