# Generated by Django 3.1.1 on 2020-10-01 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myside', '0025_auto_20201001_1118'),
        ('mycvs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cvs',
            options={'ordering': ['-name'], 'verbose_name': 'cvs', 'verbose_name_plural': 'cvs'},
        ),
        migrations.AddField(
            model_name='cvs',
            name='brand',
            field=models.CharField(max_length=20, null=True, verbose_name='편의점 브랜드'),
        ),
        migrations.AddField(
            model_name='cvs',
            name='brand_logo',
            field=models.ImageField(blank=True, null=True, upload_to='brand'),
        ),
        migrations.AddField(
            model_name='cvs',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=20, null=True, verbose_name='지점명'),
        ),
        migrations.AlterField(
            model_name='cvs',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='위도'),
        ),
        migrations.AlterField(
            model_name='cvs',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='경도'),
        ),
        migrations.AlterField(
            model_name='cvs',
            name='mycvs',
            field=models.ManyToManyField(blank=True, related_name='mycvs', to=settings.AUTH_USER_MODEL, verbose_name='내 편'),
        ),
        migrations.AlterField(
            model_name='cvs',
            name='name',
            field=models.CharField(db_index=True, max_length=20, verbose_name='지점명'),
        ),
        migrations.AlterIndexTogether(
            name='cvs',
            index_together={('id', 'slug')},
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('cvs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to='mycvs.cvs')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='myside.product')),
            ],
            options={
                'verbose_name': 'stock',
                'verbose_name_plural': 'stocks',
            },
        ),
    ]
