# Generated by Django 3.1.1 on 2020-10-02 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycvs', '0002_auto_20201001_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='재고'),
        ),
    ]
