# Generated by Django 3.1.1 on 2020-11-08 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycvs', '0003_auto_20201002_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cvs',
            old_name='mycvs',
            new_name='user',
        ),
    ]
