# Generated by Django 3.1.1 on 2020-09-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20200916_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hits',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
    ]
