# Generated by Django 3.1.1 on 2020-09-16 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20200916_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.IntegerField(default=0, verbose_name='좋아요')),
                ('bad', models.IntegerField(default=0, verbose_name='싫어요')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='community.post', verbose_name='게시글')),
            ],
        ),
    ]
