# Generated by Django 3.1.1 on 2020-09-19 13:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0004_recommend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommend',
            name='user',
        ),
        migrations.AddField(
            model_name='recommend',
            name='user',
            field=models.ManyToManyField(related_name='recommend', to=settings.AUTH_USER_MODEL),
        ),
    ]
