# Generated by Django 3.1.1 on 2020-09-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='recommend_count',
            field=models.PositiveIntegerField(default=0, verbose_name='추천'),
        ),
    ]
