# Generated by Django 3.1.1 on 2020-09-23 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0016_auto_20200922_2232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
    ]
