# Generated by Django 3.1.1 on 2020-09-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0017_auto_20200923_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='board',
            field=models.CharField(choices=[('자유게시판', '자유게시판'), ('레시피연구소', '레시피연구소')], default='자유게시판', max_length=25, verbose_name='게시판'),
            preserve_default=False,
        ),
    ]
