# Generated by Django 3.1.1 on 2020-09-25 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0019_auto_20200925_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='recommend',
            new_name='recommends',
        ),
    ]
