# Generated by Django 3.1.1 on 2020-10-03 10:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0020_auto_20200925_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='derecommends',
            field=models.ManyToManyField(blank=True, related_name='derecommends', to=settings.AUTH_USER_MODEL),
        ),
    ]
