# Generated by Django 3.1.1 on 2020-10-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myside', '0028_auto_20201008_1826'),
        ('community', '0021_post_derecommends'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, to='myside.Product'),
        ),
    ]
