# Generated by Django 3.1.1 on 2020-10-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myside', '0028_auto_20201008_1826'),
        ('community', '0022_post_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.AddField(
            model_name='post',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='posts', to='myside.Product'),
        ),
    ]
