# Generated by Django 3.1.1 on 2020-10-08 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0022_post_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='tags',
        ),
    ]
