# Generated by Django 3.1.1 on 2020-11-04 15:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0024_auto_20201008_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='derecommends',
            field=models.ManyToManyField(blank=True, related_name='post_derecommends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='recommends',
            field=models.ManyToManyField(blank=True, related_name='post_recommends', to=settings.AUTH_USER_MODEL),
        ),
    ]
