# Generated by Django 3.1.1 on 2020-09-17 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='img_profile',
            new_name='profile',
        ),
    ]
