# Generated by Django 3.1.1 on 2020-09-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, default='static/logo/person-24px.png', null=True, upload_to='profile'),
        ),
    ]
