# Generated by Django 3.1.1 on 2020-09-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_merge_20200924_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
