# Generated by Django 3.1.1 on 2020-10-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20201004_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, default='profile/default_profile.png', null=True, upload_to='profile'),
        ),
    ]
