# Generated by Django 3.1 on 2020-09-03 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=20, verbose_name='대주제')),
                ('second', models.CharField(max_length=20, verbose_name='소주제')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Like_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='제품명')),
                ('img_url', models.URLField(max_length=45, verbose_name='이미지주소')),
                ('content', models.TextField(verbose_name='설명')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('stock', models.IntegerField(verbose_name='재고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='수정날짜')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myside.category')),
            ],
            options={
                'verbose_name': '제품',
                'verbose_name_plural': '제품',
                'db_table': 'product',
            },
        ),
    ]
