# Generated by Django 3.1 on 2020-09-03 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myside', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '카테고리', 'verbose_name_plural': '카테고리'},
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
    ]
