# Generated by Django 3.1 on 2020-09-03 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myside', '0003_auto_20200903_2214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': '브랜드', 'verbose_name_plural': '브랜드'},
        ),
        migrations.AlterModelTable(
            name='brand',
            table='brand',
        ),
    ]
