# Generated by Django 3.1.1 on 2020-09-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myside', '0006_auto_20200907_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brand',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='brand'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(db_index=True, max_length=20, verbose_name='브랜드'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='img',
            field=models.ImageField(blank=True, upload_to='comments/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d'),
        ),
    ]
