# Generated by Django 3.1.1 on 2020-09-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myside', '0007_auto_20200907_1538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['-name'], 'verbose_name': 'brand', 'verbose_name_plural': 'brands'},
        ),
        
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ManyToManyField(to='myside.Brand'),
        ),
        
        migrations.AlterIndexTogether(
            name='brand',
            index_together={('id', 'slug')},
        ),
        migrations.DeleteModel(
            name='Product_has_brand',
        ),
    ]
