# Generated by Django 3.1.1 on 2020-09-13 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myside', '0008_auto_20200907_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recomment',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='myside.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=100, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myside.product', verbose_name='제품명'),
        ),
        migrations.DeleteModel(
            name='Like_recomment',
        ),
        migrations.DeleteModel(
            name='Recomment',
        ),
    ]
