# Generated by Django 3.1.1 on 2020-09-14 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myside', '0009_auto_20200914_2317'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recomment',
        ),
    ]
