# Generated by Django 3.1.1 on 2020-09-21 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myside', '0015_auto_20200921_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttag',
            name='name',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=20, unique=True, verbose_name='slug'),
        ),
        migrations.AlterUniqueTogether(
            name='producttag',
            unique_together={('name', 'slug')},
        ),
    ]
