# Generated by Django 3.1.1 on 2020-09-21 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myside', '0018_auto_20200921_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='like',
        ),
    ]
