# Generated by Django 3.1.1 on 2020-09-21 22:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myside', '0020_auto_20200922_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='comments/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='stars',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
