# Generated by Django 3.1.1 on 2020-09-24 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myside', '0022_auto_20200924_1931'),
        ('myside', '0022_auto_20200924_2241'),
    ]

    operations = [
    ]
