# Generated by Django 3.1.1 on 2020-09-27 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycvs', '0001_initial'),
        ('myside', '0023_merge_20200924_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='cvs_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cvs_name', to='mycvs.cvs', verbose_name='지점명'),
        ),
    ]
