# Generated by Django 3.1.1 on 2020-10-01 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myside', '0024_brand_cvs_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
