# Generated by Django 3.1.1 on 2020-10-02 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myside', '0025_auto_20201001_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
