# Generated by Django 3.1.1 on 2020-10-06 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myside', '0026_remove_product_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-first', '-second'], 'verbose_name': 'product_category', 'verbose_name_plural': 'product_cateogories'},
        ),
        migrations.AddField(
            model_name='category',
            name='first',
            field=models.CharField(max_length=20, null=True, verbose_name='상위카테고리'),
        ),
        migrations.AddField(
            model_name='category',
            name='second',
            field=models.CharField(max_length=20, null=True, verbose_name='하위카테고리'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='myside.category', verbose_name='category'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='category',
            index_together={('id', 'slug')},
        ),
        migrations.RemoveField(
            model_name='category',
            name='level',
        ),
        migrations.RemoveField(
            model_name='category',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='category',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='category',
            name='tree_id',
        ),
    ]
