# Generated by Django 3.1.1 on 2020-10-08 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myside', '0027_auto_20201006_1351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-first', '-second'], 'verbose_name': 'category', 'verbose_name_plural': 'cateogories'},
        ),
    ]
