# Generated by Django 3.1.1 on 2020-11-02 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myside', '0028_auto_20201008_1826'),
        ('myside', '0028_auto_20201008_1052'),
    ]

    operations = [
    ]
