# Generated by Django 3.1 on 2020-09-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='이름')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('nickname', models.CharField(max_length=20, verbose_name='별명')),
                ('password', models.CharField(max_length=45, verbose_name='비밀번호')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=16, verbose_name='성별')),
                ('birth', models.DateField()),
                ('rank', models.CharField(choices=[('admin', 'admin'), ('user', 'user')], max_length=8, verbose_name='등급')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자',
                'db_table': 'user',
            },
        ),
    ]
